version: "3"
services:
  muko-server:
    image: ggobugi1986/muko-server
    container_name: muko-server-container
    volumes:
      - /app/node_modules
      - ./muko-server:/app
  muko-web:
    image: ggobugi1986/muko-web
    volumes:
      - /app/node_modules
      - ./muko-web:/app
    stdin_open: true
  nginx:
    restart: always
    image: ggobugi1986/muko-nginx
    ports:
      - "80:80"
