version: "3"
services:
  muko-web:
    build:
      context: ./muko-web
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./muko-web:/app
    stdin_open: true
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
